### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by silkevicious** [pla1/FediPhoto#10]
Hi!
Just downloaded FediPhoto 2.7 with italian translations.
Everything good, except i saw some untranslated lines, i though i missed the translation but i checked both italian and english files but can't find them.
Is it possible to have them added?
One it's Status Config title in Status Config page.
In settings there's 'General' subtitle and 'Action after taking photo' command.
Thank you in advance!

**Comment by pla1** [comment]
Done.

Below is a screenshot of what Android Studio says we are missing.  Thanks!

[image: image.png]

**Comment by pla1** [comment]
Screenshot didn't survive email reply. Attaching via web. 

![PLA_20200622_195005](https://user-images.githubusercontent.com/426549/85345972-fe846a00-b4c1-11ea-92ee-9efc2fb5478e.png)
