### ISSUE TITLE
emoji on status TEXT fails to publish

### ISSUE THREAD

**Issue by xmgz** [pla1/FediPhoto#18]
Hi, setting activity status **text** (what is going to be published) using emoji/icon makes publishing to fail.

`🔴LIVE #running `
does not work (emoji as first character)

`LIVE 🔴 #running `
does not work (emoji at the middle)

`LIVE #running`
works fine (no emoji)

I've tested with 🏃 and  🚴  in case it was character specific, using **mastodon** account.

Thanks!

**Comment by pla1** [comment]
Fixed in version 3.5. 994f36f7532b391b9c7d2d2e060e463eb33737f5
