### ISSUE TITLE
pixelfed account not supported

### ISSUE THREAD

**Issue by xmgz** [pla1/FediPhoto#5]
this is not an issue, it's just a report for anyone reading here

- added pixelfed account (fedigram.com) without problem
- it's listed on accounts list
- selected as active account
- take photo and publish
- no error reported, but no successful publication report either

Consider check fediphoto auth or publish against pixelfed API in the future.

Thanks

**Comment by pla1** [comment]
I haven't looked but I imagine PixelFed API is totally different. I will investigate.

**Comment by pla1** [comment]
Created PixelFed issue https://github.com/pixelfed/pixelfed/issues/2244

**Comment by pla1** [comment]
Posting to PixelFed should be working in v2.6. The only caveat is PixelFed doesn't appear to accept direct posts. The over visibilities: public, unlisted, private work OK. Leaving issue open to do some more testing.
